### ISSUE TITLE
Add target npc name as a command argument

### ISSUE THREAD

**Issue by novio** [Ivaar/Windower-addons#10]

**Comment by Ivaar** [comment]
The game allows you to open trade window with any npc or monster, and still sends the trade packet.
There is always a chance that SE could decide to detect packet based addons, so you should use them at your own risk. Ashita has an addon for this, and while this addon is new, I've been using my other packet based addons like sellnpc and auctionhelper for years and still here. 

It's possible I could add this in the future, however it's not a bug so it would be low priority.

**Comment by Ivaar** [comment]
Gearswap has been intercepting /item commands and under certain conditions injects the wrong packets for players, tradeable NPC and monsters alike. When used with NPCs that allow you to open a trade window the games native /item command generates the same packet as NPC trade 0x036, all other entities it will generate a 0x037 regardless if the item is usable. I seem to remember being able to open a trade window with a monster in the past, now the game says you can not trade with that target and no packet is sent on confirmation.
I've adjusted TradeNPC to only allow 0x037 for tradeable NPC's and will look into a fix for gearswap, but I wouldn't worry too much because if they were going to do anything I would have been banned for gearswap many times.
