### ISSUE TITLE
Spam haste/refresh

### ISSUE THREAD

**Issue by mrlooolz** [Ivaar/Windower-addons#15]
Hello. I set haste/refresh to 5 mins and i switch it on. It keeps spamming Haste/refresh.

**Comment by Ivaar** [comment]
The setting is for how many seconds to recast before the spell is due to wear off.
So `//geo recast buff 5 10`, would recast haste between 5 to 10 seconds before it is due to wear off.
The idea around this was so it would not seem like a bot by casting every X seconds or reapplying buffs the moment they wear. Base duration for haste is 3 mins and 2.5mins for refresh, do you have some kind of duration enhancements?

**Comment by mrlooolz** [comment]
i do 5/5 telchnie + shield.

it starts to spam haste. so like haste, when cd is back haste etc. its like it doesnt ready that i got the buff. I read the lua and so the recast command. but not sure why?

**Comment by mrlooolz** [comment]
I tried and still the same thing :(

**Comment by Ivaar** [comment]
Typo on line 384 change to
`timers[spell.enl:lower()][target.name:lower()] = os.time()+spell.dur`

**Comment by mrlooolz** [comment]
ill have to check tomorrow. do i keep like 220 the orginal or one posted above?
