### ISSUE TITLE
Honor March

### ISSUE THREAD

**Issue by Gotenn** [Ivaar/Windower-addons#8]
I've added Honor march to the sing_get area, but I don't know how to find the spell ID to add it to the sing_ids lua.  How would I go about adding it so it will cast Honor March?

**Comment by Ivaar** [comment]
Honor March id is 417,  [res/spells.lua](https://github.com/Windower/Resources/blob/master/lua/spells.lua) inside your windower directory. Leave the issue open so I remember to add it.

**Comment by Gotenn** [comment]
I've got it where he will cast it, but it doesn't recognize the buff, so it will cast it over and over.  I can wait for your fix if its just easier to wait.

**Comment by Gotenn** [comment]
Sorry for the late response, and I did both of these, and my character keeps recasting honor march over and over.

**Comment by Ivaar** [comment]
I haven't really played in a few years and have limited knowledge of changes made since then, does honor march grant a special buff, also are you testing this solo or in a party? [Could you save and load this as an addon](https://gist.github.com/Ivaar/3a6a83729c7fac6cbcecbd2d2ff98a41), cast honor march and tell me what it outputs to your chatlog.
`

**Comment by Gotenn** [comment]
effect 214, message 230

**Comment by Ivaar** [comment]
Added marsyas to gear calculations and I believe this will solve your issue. You will still have to make the changes discussed above as they will break the addon for non aeonic bards. I will have to recode at some point, the addon deserves an overhaul and gear calculations are no longer necessary since SE now sends packets with buff durations for both player and party members.

**Comment by Gotenn** [comment]
Thank you, It now works with all of the above, Also worth mentioning to anyone who sees this that you have to add: 
sets.precast.FC["Honor March"] = set_combine(sets.precast.FC.BardSong,{range="Marsyas"})
sets.midcast["Honor March"] = set_combine(sets.midcast.SongEffect,{range="Marsyas"})
(or equivalent) 
Into your lua so that your horn will swap before the cast of Honor March.
I'll let you close this out if your happy where it ended, it works with those changes.

**Comment by Chiaia** [comment]
I actually added the rest of the new gear and added honor march into this addon after my last pull request. Though I made Honor March it's own thing because there are times you actually would want the regular 2 marchs over honor march.

**Comment by Ivaar** [comment]
Please submit a new PR and I will happily merge your changes. Be sure to update the readme if necessary.
